### ISSUE TITLE
map wont load on non vr mode

### ISSUE THREAD

**Issue by Aarontseu9** [OpenViva/OpenViva#23]
Map wont load on non vr mode
![Screenshot 2022-07-01 224253](https://user-images.githubusercontent.com/95078267/176916546-4444eac8-d6ce-454a-8a53-b922e38b54cb.png)

**Comment by funmaker** [comment]
Which game version?

**Comment by funmaker** [comment]
Wait for 0.2. It'll be based on Viva 0.8 instead and many of bugs like that will probably not be present.

**Comment by DawnShadow** [comment]
You have to open the menu and create a new save.
