### ISSUE TITLE
Loli is unresponsive. How to reset her

### ISSUE THREAD

**Issue by dvdvideo1234** [OpenViva/OpenViva#27]
To reproduce:
1. Go to peaches tree and grab some peaches
2. She is dirty so try to make her take a bath
3. She stays and watch silently, then grab her an put her in the bathtub :D
4. She is stuck so dress her up.
![image](https://user-images.githubusercontent.com/9112662/201172003-b723c51f-7c94-4057-b6da-c19f109864ff.png)

**Comment by dvdvideo1234** [comment]
Sometimes her take a bath makes her disappear,and sometime she is stuck within a wall
![image](https://user-images.githubusercontent.com/9112662/201205208-71137f9b-25c6-4d3e-8648-4ee99f28567a.png)

**Comment by Foxify52** [comment]
Bathing is broken. The only two ways to reset a character are to re-spawn them or reset the game.
