### ISSUE TITLE
Source code for mod-support branch fails to compile in Unity

### ISSUE THREAD

**Issue by stayandwait** [OpenViva/OpenViva#28]
Do you know what the paid version of the package you are using? You don't specify this. This would fix the complication issue.

**Comment by stayandwait** [comment]
![image](https://user-images.githubusercontent.com/15825041/207931621-252bda93-51f9-4f36-a965-31d8915c9538.png)

**Comment by stayandwait** [comment]
![image](https://user-images.githubusercontent.com/15825041/207931753-cb9c6f98-27f8-44eb-be04-346b57d4e503.png)

**Comment by stayandwait** [comment]
![image](https://user-images.githubusercontent.com/15825041/207931801-b8bb4ea8-6b44-4ff9-a8ea-3eeff88a5db2.png)

**Comment by stayandwait** [comment]
![image](https://user-images.githubusercontent.com/15825041/207932322-28b84a68-4a41-4727-909b-b09a1b4ef7e1.png)

**Comment by Foxify52** [comment]
from the unity asset store: Horse animset pro, Nature Assets - Bamboo pack, Nature Assets - Foliage Package
from sketchfab: https://sketchfab.com/3d-models/chicken-4ab19d3a675343959815ae770f8b178e
